version: "3.8"

services:
  database:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
